"""
app/db/tenant_context.py
Tenant transaction context helper (W1-031).

This is the ONLY way to execute tenant-scoped database operations.
It enforces the following contract:

  1. Receives a validated tenant UUID from authenticated server context
     (NEVER from a request body field).
  2. Starts one transaction on the provided connection.
  3. Sets a transaction-local PostgreSQL setting: app.tenant_id = <uuid>.
  4. Executes all reads, writes, and tenant audits within that transaction.
  5. Commits on success; rolls back on any exception.
  6. The transaction-local setting auto-clears after commit/rollback,
     preventing context leakage across pooled connections.

RLS policies on tenant-owned tables use:
  tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid

Which means:
  - If context is not set: no rows visible (NULLIF returns NULL → no match)
  - If context is set to wrong tenant: only that tenant's rows visible
  - Cross-tenant access is impossible even with intentionally unfiltered queries

Security invariants:
  - No disable_tenant_checks flag
  - No is_admin_bypass mechanism
  - No optional tenant_id override
  - Application queries ALSO filter by tenant_id for defence-in-depth and index use
"""
from __future__ import annotations

import uuid
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncConnection

from app.core.errors import ForbiddenError


def _validate_tenant_uuid(tenant_id: uuid.UUID | str) -> str:
    """
    Validate that the tenant_id is a properly formed UUID.
    Raises ForbiddenError if not — prevents SQL injection via context setting.
    Returns the string representation.
    """
    try:
        parsed = uuid.UUID(str(tenant_id))
        return str(parsed)
    except (ValueError, AttributeError) as e:
        raise ForbiddenError("Invalid tenant context.") from e


@asynccontextmanager
async def tenant_transaction(
    conn: AsyncConnection,
    tenant_id: uuid.UUID,
) -> AsyncGenerator[AsyncConnection, None]:
    """
    Context manager for tenant-scoped database operations.

    Usage:
        async with tenant_transaction(conn, validated_tenant_uuid) as txn:
            result = await txn.execute(
                sa.select(Contact).where(Contact.tenant_id == tenant_id)
            )

    The tenant_id MUST come from server-side authentication/membership validation.
    Never pass a tenant_id from a client request body.
    """
    tid_str = _validate_tenant_uuid(tenant_id)

    async with conn.begin():
        # Set tenant context transaction-locally (true = resets after transaction ends)
        # Use a bound parameter to prevent any SQL injection possibility
        await conn.execute(
            sa.text("SELECT set_config('app.tenant_id', :tid, true)"),
            {"tid": tid_str},
        )
        try:
            yield conn
        except Exception:
            # Roll back is handled by conn.begin() context manager
            raise
        # On clean exit: conn.begin() commits; transaction-local setting auto-clears


@asynccontextmanager
async def provisioning_transaction(
    conn: AsyncConnection,
    new_tenant_id: uuid.UUID,
) -> AsyncGenerator[AsyncConnection, None]:
    """
    Special context for new tenant provisioning.
    Sets the tenant context to a server-generated UUID before any scoped writes,
    allowing the atomic creation of: tenant + subscription + membership + settings.

    The new_tenant_id MUST be generated by the server (uuid.uuid4()),
    never supplied by the client.
    """
    yield conn
    async with tenant_transaction(conn, new_tenant_id):
        yield conn
